version: '3.9'

services:
  web:
    build:
      context: ./app        
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app          
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
